### ISSUE TITLE
[BUG] report cannot be created

### ISSUE THREAD

**Issue by fmdl** [odoo/upgrade-util#61]
Hi @xavieralt

This commit https://github.com/odoo/upgrade-util/commit/efc5663171421755c94cc469f6db6414d5fd3b80 create a fail during migration in V10.

```
2024-03-26 01:38:20 INFO: 2024-03-26 10:24:19,929 1086 INFO db_1433576 odoo.modules.loading: Modules loaded.
2024-03-26 01:38:20 INFO: 2024-03-26 10:24:19,935 1086 INFO db_1433576 odoo.addons.base.maintenance.migrations.util.report: {'Disabled views': [({'id': 1143, 'name': u'res.company.form.purchase.inherit'}, False)], 'Fields renamed': [('\n<details>\n  <summary>\n    Models <kbd>hr.attendance</kbd>: the field <kbd>name</kbd> has been renamed to <kbd>check_in</kbd>. The following server actions may need update.\n  </summary>\n  <ul><li><a target="_blank" href="/web?debug=1#view_type=form&amp;model=ir.actions.server&amp;action=&amp;id=1071">FIX Qty Therorique</a></li></ul>\n</details>\n            ', True)]}
2024-03-26 01:38:20 INFO: 2024-03-26 10:24:19,945 1086 WARNING db_1433576 odoo.modules.loading: Transient module states were reset
2024-03-26 01:38:20 INFO: 2024-03-26 10:24:19,945 1086 ERROR db_1433576 odoo.modules.registry: Failed to load registry
2024-03-26 01:38:20 INFO: Traceback (most recent call last):
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/modules/registry.py", line 83, in new
2024-03-26 01:38:20 INFO:     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/modules/loading.py", line 465, in load_modules
2024-03-26 01:38:20 INFO:     model._register_hook()
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/mail/0.0.0/pre-report-migration.py", line 28, in _register_hook
2024-03-26 01:38:20 INFO:     util.announce_migration_report(self.env.cr)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/util/report.py", line 101, in announce_migration_report
2024-03-26 01:38:20 INFO:     message = render(report, values=values)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
2024-03-26 01:38:20 INFO:     return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 251, in render
2024-03-26 01:38:20 INFO:     self.compile(template, options)(self, body.append, values or {})
2024-03-26 01:38:20 INFO:   File "<decorator-gen-21>", line 2, in compile
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/tools/cache.py", line 87, in lookup
2024-03-26 01:38:20 INFO:     value = d[key] = self.method(*args, **kwargs)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 73, in compile
2024-03-26 01:38:20 INFO:     return super(IrQWeb, self).compile(id_or_xml_id, options=options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 290, in compile
2024-03-26 01:38:20 INFO:     raise QWebException("Error when compiling AST", e, path, etree.tostring(node[0]), name)
2024-03-26 01:38:20 INFO: QWebException: forbidden opcode(s) in 'get_anchor_link_to_record(*message[0])'
2024-03-26 01:38:20 INFO: Traceback (most recent call last):
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 280, in compile
2024-03-26 01:38:20 INFO:     body = self._compile_node(element, _options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 635, in _compile_node
2024-03-26 01:38:20 INFO:     return body + self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     return super(QWeb, self)._compile_directive_tag(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 879, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     content = self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 635, in _compile_node
2024-03-26 01:38:20 INFO:     return body + self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 1009, in _compile_directive_foreach
2024-03-26 01:38:20 INFO:     def_name = self._create_def(options, self._compile_directives(el, options), prefix='foreach', lineno=el.sourceline)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     return super(QWeb, self)._compile_directive_tag(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 879, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     content = self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 626, in _compile_node
2024-03-26 01:38:20 INFO:     return self._compile_static_node(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 706, in _compile_static_node
2024-03-26 01:38:20 INFO:     content = self._compile_directive_content(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 635, in _compile_node
2024-03-26 01:38:20 INFO:     return body + self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 971, in _compile_directive_if
2024-03-26 01:38:20 INFO:     orelse = self._compile_node(next_el, dict(options, t_if=True))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 635, in _compile_node
2024-03-26 01:38:20 INFO:     return body + self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 960, in _compile_directive_elif
2024-03-26 01:38:20 INFO:     compiled = self._compile_directive_if(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 979, in _compile_directive_if
2024-03-26 01:38:20 INFO:     body=self._compile_directives(el, options),
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     return super(QWeb, self)._compile_directive_tag(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 879, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     content = self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 626, in _compile_node
2024-03-26 01:38:20 INFO:     return self._compile_static_node(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 706, in _compile_static_node
2024-03-26 01:38:20 INFO:     content = self._compile_directive_content(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 626, in _compile_node
2024-03-26 01:38:20 INFO:     return self._compile_static_node(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 706, in _compile_static_node
2024-03-26 01:38:20 INFO:     content = self._compile_directive_content(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 626, in _compile_node
2024-03-26 01:38:20 INFO:     return self._compile_static_node(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 706, in _compile_static_node
2024-03-26 01:38:20 INFO:     content = self._compile_directive_content(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 635, in _compile_node
2024-03-26 01:38:20 INFO:     return body + self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 1009, in _compile_directive_foreach
2024-03-26 01:38:20 INFO:     def_name = self._create_def(options, self._compile_directives(el, options), prefix='foreach', lineno=el.sourceline)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/addons/web_editor/models/ir_qweb.py", line 55, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     return super(QWeb, self)._compile_directive_tag(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 879, in _compile_directive_tag
2024-03-26 01:38:20 INFO:     content = self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 940, in _compile_directive_content
2024-03-26 01:38:20 INFO:     body.extend(self._compile_node(item, options))
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 635, in _compile_node
2024-03-26 01:38:20 INFO:     return body + self._compile_directives(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 656, in _compile_directives
2024-03-26 01:38:20 INFO:     return compile_handler(el, options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 1053, in _compile_directive_raw
2024-03-26 01:38:20 INFO:     content = self._compile_widget(el, el.attrib.pop('t-raw'), field_options)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 1105, in _compile_widget
2024-03-26 01:38:20 INFO:     self._compile_expr0(expression),
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 1422, in _compile_expr0
2024-03-26 01:38:20 INFO:     return self._compile_expr(expr)
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 304, in _compile_expr
2024-03-26 01:38:20 INFO:     expr
2024-03-26 01:38:20 INFO:   File "/home/odoo/src/odoo/10.0/odoo/tools/safe_eval.py", line 138, in assert_valid_codeobj
2024-03-26 01:38:20 INFO:     raise ValueError("forbidden opcode(s) in %r" % expr)
2024-03-26 01:38:20 INFO: ValueError: forbidden opcode(s) in 'get_anchor_link_to_record(*message[0])'
2024-03-26 01:38:20 INFO: 
2024-03-26 01:38:20 INFO: Error when compiling AST
2024-03-26 01:38:20 INFO: ValueError: forbidden opcode(s) in 'get_anchor_link_to_record(*message[0])'
2024-03-26 01:38:20 INFO: Template: mail.report_migration
2024-03-26 01:38:20 INFO: Path: /t/t/ul/t[1]
2024-03-26 01:38:20 INFO: Node: <t t-if="category in ['Disabled views', 'Overridden views']" t-tag="t" t-content="True">
2024-03-26 01:38:20 INFO:         <t t-set="view_message_types" t-value="{           'Overridden views': ['The below standard views have been overriden with their original content during the migration because the changes made in them were no longer valid.', '%(xml_id)s'],           'Disabled views': ['The below custom views have been disabled during the migration because they were no longer valid.', '%(name)s'],         }"/>
2024-03-26 01:38:20 INFO:         <t t-set="message_type" t-value="view_message_types[category]"/>
2024-03-26 01:38:20 INFO:         <li><details t-if="messages[category]">
2024-03-26 01:38:20 INFO:           <summary>
2024-03-26 01:38:20 INFO:             <t t-esc="message_type[0]"/>
2024-03-26 01:38:20 INFO:           </summary>
2024-03-26 01:38:20 INFO:           <ul>
2024-03-26 01:38:20 INFO:           <t t-foreach="messages[category]" t-as="message">
2024-03-26 01:38:20 INFO:             <t t-set="view" t-value="message[0]"/>
2024-03-26 01:38:20 INFO:             <li>
2024-03-26 01:38:20 INFO:               <t t-if="view.get('copy_id')">
2024-03-26 01:38:20 INFO:                 <t t-esc="message_type[1] % view"/>
2024-03-26 01:38:20 INFO:                 &amp;nbsp;
2024-03-26 01:38:20 INFO:                 <t t-raw="get_anchor_link_to_record('ir.ui.view', view['id'], 'Original', action_id=action_view_id)"/>
2024-03-26 01:38:20 INFO:                 &amp;nbsp;
2024-03-26 01:38:20 INFO:                 <t t-raw="get_anchor_link_to_record('ir.ui.view', view['copy_id'], 'Copy', action_id=action_view_id)"/>
2024-03-26 01:38:20 INFO:               </t>
2024-03-26 01:38:20 INFO:               <t t-if="not view.get('copy_id')">
2024-03-26 01:38:20 INFO:                   <t t-raw="get_anchor_link_to_record('ir.ui.view', view['id'], message_type[1] % view, action_id=action_view_id)"/>
2024-03-26 01:38:20 INFO:               </t>
2024-03-26 01:38:20 INFO:             </li>
2024-03-26 01:38:20 INFO:           </t>
2024-03-26 01:38:20 INFO:           </ul>
2024-03-26 01:38:20 INFO:         </details></li>
2024-03-26 01:38:20 INFO:       </t>


```

**Comment by KangOl** [comment]
Ho! The unpacking call use the `CALL_FUNCTION_VAR` opcode, but it has only been supported with the python3 support[^1]. We will need to manually unpack it.
```
❯ echo 'get_anchor_link_to_record(*message[0])' | python2 -m dis
  1           0 LOAD_NAME                0 (get_anchor_link_to_record)
              3 LOAD_NAME                1 (message)
              6 LOAD_CONST               0 (0)
              9 BINARY_SUBSCR
             10 CALL_FUNCTION_VAR        0
             13 POP_TOP
             14 LOAD_CONST               1 (None)
             17 RETURN_VALUE
```

[^1]: https://github.com/odoo/odoo/commit/6e9d29df1d6335d41a950633478551c78484a794#diff-4af16af8fba18ea46e1f800bba43e1736b41e805d645656a0915cb05e5f5cc0fR97-R98
